### ISSUE TITLE
pypi update for use in radiolog Dec. 2022

### ISSUE THREAD

**Issue by caver456** [ncssar/sartopo_python#46]
see https://github.com/ncssar/radiolog/issues/598 - add a separate issue in this repo for each feature needed by radiolog, but, also clean up bugs in this repo that existed before Dec. 2022

- [x] compare sartopo_python.py from various locations and repos (plans_console etc.), to bring the latest greatest back into this repo
- [x] fix new issues needed for radiolog
  - [x] #60 (possibly required for #48 and #50)
  - [x] #48 
  - [x] #49 
  - [x] #50  
- [x] fix pre-existing bug issues from this repo
  - [ ] ~~#22~~ (not truly necessary yet)
  - [x] #27 
  - [x] #34 
  - [x] #37 
  - [x] #39 
  - [x] #42  
- [x] fix any new bugs discovered since the previous commit, which may be due to new CTD or online version
  - [x] #52 
- [x] #68
- [ ] ~~#70~~ not enough need for this invasive change before release of 2.0.0
- [x] #72
- [x] #74
- [x] #76
- [ ] ~~#77~~ maybe not fixable using the API
- [x] #80
- [x] update README and docs to reference caltopo_python pypi, repo, and readthedocs
- [x] publish readthedocs for sartopo_python
- [x] release new package version in pypi

**Comment by caver456** [comment]
For the first checklist item: there are several different versions of sartopo_python.py lying around, and they history doesn't appear to be linear.  So, this will take a little while to figure out.  Ultimately, a fresh commit to this repo should be done as soon as the latest-greatest is determined/combined from existing files, and then the other bug fixes and features should be added afterwards.

**Comment by caver456** [comment]
Finished the comparisons at [this google doc](https://docs.google.com/spreadsheets/d/1oCUwJ9GI76-hET7yoh2nbE7XUBiQ0g9C4Ni_97hBH10/edit?usp=sharing); copied the latest to this repo and did a commit.

**Comment by caver456** [comment]
All done, with release of 2.0.0 and caltopo_python 1.0.0, on github, and on pypi, with readthedocs for both.
